---
title: "test rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(RColorBrewer)

theme_update(plot.title = element_text(hjust = 0.5, face = "bold"))
data(mtcars)

library(readr)
uiuc_gpa_dataset <- read_csv("~/Git/r-testing/uiuc-gpa-dataset.csv", 
     col_types = cols(Year = col_character(), 
         Number = col_character()))

```

## Plotting

```{r plotting1}
ggplot(data = mtcars, aes(x=disp,y=mpg)) +
  geom_point(color = 'blue') +
  labs(title = "Displacement vs MPG", x = "Displacement", y = "MPG")
```

## Setting Up UIUC dataset

```{r data_setup}

gradeCols = c('A+','A','A-',
              'B+','B','B-',
              'C+','C','C-',
              'D+','D','D-',
              'F','W'       )

gradeWeights = c(4, 4, 3.67,
                 3.33, 3, 2.67,
                 2.33, 2, 1.67,
                 1.33, 1, .67,
                 0, 0       )

uiuc_gpa_dataset$numStudents = rowSums(uiuc_gpa_dataset[,gradeCols])
for (x in 1:length(uiuc_gpa_dataset$Year)) {
  uiuc_gpa_dataset$avgGPA[x] = sum(uiuc_gpa_dataset[x,gradeCols] * gradeWeights) / uiuc_gpa_dataset$numStudents[x]
  }


```

## plotting GPA dataset

```{r plotting2}

uiuc2020 = subset(uiuc_gpa_dataset, Year == 2020)

ggplot(data=uiuc2020,aes(x=avgGPA, color = YearTerm)) +
  geom_histogram(bins = 500)

lowest_profs = uiuc_gpa_dataset %>%
  group_by(`Primary Instructor`) %>%
  filter(n()>10) %>%
  summarize(mean = mean(avgGPA))

```